name: Arduino-CLI CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          cli-compile-flags: |
            - --warnings="all"

          fqbn: esp32:esp32:esp32c3m1IKit
          sketch-paths: |
            - .
          libraries: |
            - name: AHT20
            - name: WS2812FX
            - name: ArduinoJson
            - name: PMS Library
            - name: TaskScheduler
            - name: jled
            - name: WiFiManager
            - source-url: https://github.com/Sensirion/arduino-core.git
            - source-url: https://github.com/Sensirion/arduino-i2c-scd4x.git
